name: CI

on:
  pull_request:
    branches: ['main', 'release/**']

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  #
  # golangci-lint
  #
  linters:
    name: Linters
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-go
      - run: ./tools/scripts/install-golangci-lint
      - run: |
          make lint-golang  

  #
  # Project checks
  #
  project:
    name: Project Checks
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4
        with:
          path: src/github.com/kcrow-io/kcrow
          fetch-depth: 100

      - uses: ./src/github.com/kcrow-io/kcrow/.github/actions/install-go

      - name: verify build
        run: |
          make binaries
        working-directory: src/github.com/kcrow-io/kcrow

  
  integration-linux:
    name: Linux Integration
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    needs: [ "project" ]

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4
      - uses: yylt/k3s-gha@master
        with:
          k3s_arguments: "--disable=servicelb,traefik,local-storage,metrics-server,runtimes --disable-helm-controller  --disable-cloud-controller --disable-network-policy"
          containerd_toml_path: "./tests/config/containerd-1.x.toml"

      - uses: ./.github/actions/install-go
      - name: run e2e
        env:
          KUBECONFIG: ${{ github.workspace }}/k3s.yaml
        shell: bash
        run: |
          set -ex
          make
          nohup sudo -E output/*/bin/daemon daemon -v=4 --kubeconfig=./k3s.yaml >log 2>&1  &
          sleep 2
          make e2e
          cat log
