name: CI

on:
  pull_request:
    branches: ['main', 'release/**']

  workflow_call:
    inputs:
      ref:
        description: 'sha, tag, branch'
        required: true
        type: string
        default: main

  workflow_dispatch:
      ref:
        description: 'sha, tag, branch'
        required: true
        default: main

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  #
  # lint and build
  #
  project:
    name: Linters and Build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-go
      - run: ./tools/scripts/install-golangci-lint

      - name: Lint Test
        run: |
          make lint-golang 

      - name: Build Test
        run: |
          make build-bin

  #
  # integration test
  #
  integration-linux:
    name: Linux Integration Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    needs: [ project ]

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-go

      - name: Setup K3s 
        uses: yylt/k3s-gha@master
        with:
          k3s_arguments: "--disable=servicelb,traefik,local-storage,metrics-server,runtimes --disable-helm-controller  --disable-cloud-controller --disable-network-policy"
          containerd_toml_path: "./tests/config/containerd-1.x.toml"

      - name: Integration Test
        env:
          KUBECONFIG: ${{ github.workspace }}/k3s.yaml
        shell: bash
        run: |
          set -ex
          make
          nohup sudo -E output/*/bin/daemon daemon -v=4 --kubeconfig=./k3s.yaml >log 2>&1  &
          sleep 2
          make e2e
          cat log
